/*
 * difference.java
 *
 * Created on 1 June, 2020, 12:57 PM
 */

package bcd;

/**
 *
 * @author  Admin
 */
public class difference extends javax.swing.JFrame {
    
    /** Creates new form difference */
    public difference() {
        initComponents();
        setSize(950, 775);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 30));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Difference between BCD and binary");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 670, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\copy1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 394, 559);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jTextArea1.setRows(5);
        jTextArea1.setText("In BCD we can use the binary \nnumber from 0000-1001 only,\nwhich are the decimal equivalent \nfrom 0-9 respectively.\n \nThis is the main difference \nbetween Binary number and \nbinary coded decimal. \n\nFor 0 to 9 decimal numbers \nboth binary and BCD is equal\nbut when decimal number is \nmore than one bit BCD differs\nfrom binary.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 160, 430, 420);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 630, 150, 37);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 630, 150, 37);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\87992.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 970, 730);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-982)/2, (screenSize.height-757)/2, 982, 757);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Table obj = new Table();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu obj=new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new difference().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
