/*
 * dynamic.java
 *
 * Created on 1 June, 2020, 3:00 PM
 */

package bcd;

import javax.swing.JOptionPane;

/**
 *
 * @author  Admin
 */
public class dynamic extends javax.swing.JFrame {
    
    /** Creates new form dynamic */
    public dynamic() {
        initComponents();
        setSize(918,580);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LET'S TRY SOME DYNAMIC VALUES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 848, 64);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter a decimal value:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 210, 281, 36);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 28));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BCD:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 300, 69, 33);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(380, 210, 160, 40);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 300, 130, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 430, 250, 37);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 430, 160, 37);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(350, 300, 140, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(530, 300, 140, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(700, 300, 150, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(Enter 4 digits)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(560, 220, 155, 28);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 430, 150, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\PPMnOZM.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -10, 900, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-918)/2, (screenSize.height-625)/2, 918, 625);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu obj = new Menu();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        String str=jTextField1.getText();
        if(str.length()>4 || str.length()<4){
            JOptionPane.showMessageDialog(this," Please Enter 4 digit number");
        } else{
            char c1=(str.charAt(0));
            int a=(int)c1;
            System.out.println(a);
            char c2=str.charAt(1);
            char c3=str.charAt(2);
            char c4=str.charAt(3);
            /*if (c1!='0'||c1!='1'|| c1!='2' ||c1!='3'||c1!='4'|| c1!='5'||c1!='6'||c1!='7'|| c1!='8'|| c1!='9'){
                JOptionPane.showMessageDialog(this, "pLEASE eNTER nUMERIC vALUES");
            }
             if (c2!='0'||c2!='1'|| c2!='2' ||c2!='3'||c2!='4'|| c2!='5'||c2!='6'||c2!='7'|| c2!='8'|| c2!='9'){
                JOptionPane.showMessageDialog(this, "pLEASE eNTER nUMERIC vALUES");
             }
             if (c3!='0'||c3!='1'|| c3!='2' ||c3!='3'||c3!='4'|| c3!='5'||c3!='6'||c3!='7'|| c3!='8'|| c3!='9'){
                JOptionPane.showMessageDialog(this, "pLEASE eNTER nUMERIC vALUES");
             }
             if (c4!='0'||c4!='1'|| c4!='2' ||c4!='3'||c4!='4'|| c4!='5'||c4!='6'||c4!='7'|| c4!='8'|| c4!='9'){
                JOptionPane.showMessageDialog(this, "pLEASE eNTER nUMERIC vALUES");
             }*/
            if((int)c1<48||(int)c1>57){
                JOptionPane.showMessageDialog(this, "Please enter valid value at place 1");
            }
             if((int)c2<48||(int)c2>57){
                JOptionPane.showMessageDialog(this, "Please enter valid value at place 2");
            }
             if((int)c3<48||(int)c3>57){
                JOptionPane.showMessageDialog(this, "Please enter valid value at place 3");
            }
             if((int)c4<48||(int)c4>57){
                JOptionPane.showMessageDialog(this, "Please enter valid value at place 4");
            }
            if(c1=='0'){
                jTextField2.setText("0000");
            }
            if(c2=='0'){
                jTextField3.setText("0000");
            }
            if(c3=='0'){
                jTextField4.setText("0000");
            }
            if(c4=='0'){
                jTextField5.setText("0000");
            }
            if(c1=='1'){
                jTextField2.setText("0001");
            }
            if(c2=='1'){
                jTextField3.setText("0001");
            }
            if(c3=='1'){
                jTextField4.setText("0001");
            }
            if(c4=='1'){
                jTextField5.setText("0001");
            }
            if(c1=='2'){
                jTextField2.setText("0010");
            }
            if(c2=='2'){
                jTextField3.setText("0010");
            }
            if(c3=='2'){
                jTextField4.setText("0010");
            }
            if(c4=='2'){
                jTextField5.setText("0010");
            }
            if(c1=='3'){
                jTextField2.setText("0011");
            }
            if(c2=='3'){
                jTextField3.setText("0011");
            }
            if(c3=='3'){
                jTextField4.setText("0011");
            }
            if(c4=='3'){
                jTextField5.setText("0011");
            }
            if(c1=='4'){
                jTextField2.setText("0100");
            }
            if(c2=='4'){
                jTextField3.setText("0100");
            }
            if(c3=='4'){
                jTextField4.setText("0100");
            }
            if(c4=='4'){
                jTextField5.setText("0100");
            }
            if(c1=='5'){
                jTextField2.setText("0101");
            }
            if(c2=='5'){
                jTextField3.setText("0101");
            }
            if(c3=='5'){
                jTextField4.setText("0101");
            }
            if(c4=='5'){
                jTextField5.setText("0101");
            }
            if(c1=='6'){
                jTextField2.setText("0110");
            }
            if(c2=='6'){
                jTextField3.setText("0110");
            }
            if(c3=='6'){
                jTextField4.setText("0110");
            }
            if(c4=='6'){
                jTextField5.setText("0110");
            }
            if(c1=='7'){
                jTextField2.setText("0111");
            }
            if(c2=='7'){
                jTextField3.setText("0111");
            }
            if(c3=='7'){
                jTextField4.setText("0111");
            }
            if(c4=='7'){
                jTextField5.setText("0111");
            }
            if(c1=='8'){
                jTextField2.setText("1000");
            }
            if(c2=='8'){
                jTextField3.setText("1000");
            }
            if(c3=='8'){
                jTextField4.setText("1000");
            }
            if(c4=='8'){
                jTextField5.setText("1000");
            }
            if(c1=='9'){
                jTextField2.setText("1001");
            }
            if(c2=='9'){
                jTextField3.setText("1001");
            }
            if(c3=='9'){
                jTextField4.setText("1001");
            }
            if(c4=='9'){
                jTextField5.setText("1001");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dynamic().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    
}
