/*
 * examples.java
 *
 * Created on 1 June, 2020, 12:14 PM
 */

package bcd;

/**
 *
 * @author  Admin
 */
public class examples extends javax.swing.JFrame {
    
    /** Creates new form examples */
    public examples() {
        initComponents();
        setSize(995,830);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.orange);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 41));
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("GLANCE ON SOME EXAMPLES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 40, 690, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\568-to-bcd-code.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 362, 204);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\img00056.gif")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 360, 574, 348);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 740, 190, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\J6SsKx.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-19, -4, 1030, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-842)/2, 1024, 842);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Menu obj=new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examples().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
