/*
 * Table.java
 *
 * Created on 31 May, 2020, 9:55 PM
 */

package bcd;

import java.awt.Color;

/**
 *
 * @author  Admin
 */
public class Table extends javax.swing.JFrame {
    
    /** Creates new form Table */
    public Table() {
        initComponents();
        setSize(970,583);
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jTextArea1.setForeground(new java.awt.Color(204, 0, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("1)BCD takes advantage of the fact \nthat any one decimal numeral \ncan be represented by a four bit \npattern. \n2)The most obvious way of \nencoding digits is Natural BCD), \nwhere each decimal digit is \nrepresented by its corresponding \nfour-bit binary value, \nas shown in the following table. \nThis is also called \"8421\" .");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 100, 440, 340);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\ICT Hackathon\\table-bcd.PNG")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 80, 313, 398);

        jButton1.setBackground(java.awt.Color.pink);
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(773, 481, 130, 40);

        jButton2.setBackground(java.awt.Color.pink);
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 490, 90, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel2.setText("HOW TO CONVERT BCD FROM DECIMAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 30, 640, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Sem-2\\blue-1273089_960_720.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 970, 630);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-978)/2, (screenSize.height-583)/2, 978, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       difference obj = new difference();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Introduction obj = new Introduction();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
